---
name: Deploy to Firebase Hosting on request

on: repository_dispatch

env:
  NEXT_DATOCMS_API_TOKEN: ${{secrets.NEXT_DATOCMS_API_TOKEN}}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm -f package-lock.json && npm install
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIERRE_TOURON_D6705 }}
          channelId: live
          projectId: pierre-touron-d6705
 